###
POST http://localhost:3000/create-user
Content-Type: application/json

{
    "name":"pedro sampaio",
    "age":26
}


###
GET http://localhost:3000/find-user?name=pedro sampaio


###
GET http://localhost:3000/find-user-all
